.\"
.\" $Id: xd.1,v 1.4 2019/05/02 10:21:05 urs Exp $
.\"
.TH XD 1 "Jan 13, 2019" "" "User Commands"
.SH NAME
xd \- hexdump
.SH SYNOPSIS
.B xd
.RI [ \fB\-g\fP\ group ]
.RI [ file " ...]"
.SH DESCRIPTION
.B xd
dumps the input files or standard input in hexadecimal and ASCII.
.B xd
is less flexible than
.BR od ", " xxd ", and " hexdump
but it is a
.I lot
faster than these.
.SH OPTIONS
.TP
.BI \-g \ group
Set the number of bytes grouped together.  Groups are separated by a
single space.  The default is 2 bytes per group.
.SH "SEE ALSO"
.BR od "(1), " xxd "(1), " hexdump (1)
.SH AUTHOR
Urs Thuermann <urs@isnogud.escape.de>
